# chromium-bsu
# Autogenerated from man page /usr/lib/jvm/default/man/man6/chromium-bsu.6.gz
complete -c chromium-bsu -s f -l fullscreen -d 'runs in fullscreen mode'
complete -c chromium-bsu -s w -l window -d 'runs in a window'
complete -c chromium-bsu -o na -l noaudio -d 'does not initialize audio'
complete -c chromium-bsu -s v -l vidmode -d 'selects video mode. br mode . br 0 =  512 x  384 . br 1 =  640 x  480 '
complete -c chromium-bsu -o nb -l noblend -d 'disables blending.  (OpenGL)'
complete -c chromium-bsu -o nt -l notexborder -d 'do not set tex border color.  (OpenGL)'
complete -c chromium-bsu -s V -l version -d 'show version information and exit'
complete -c chromium-bsu -l debug -d 'enable the display of debug information'

