# mumble
# Autogenerated from man page /usr/lib/jvm/default/man/man1/mumble.1.gz
complete -c mumble -s h -l help -d 'Show the help text and exit. HP -m, --multiple'
complete -c mumble -s m -l multiple -d 'Allow multiple instances of the client to be started'
complete -c mumble -s c -l config -d 'Specify an alternative configuration file'
complete -c mumble -s n -l noidentity -d 'Suppress loading of identity files (i. e. , certificates. )'
complete -c mumble -o jn -l jackname -d 'Set custom Jack client name'
complete -c mumble -l license -d 'Show the Mumble license'
complete -c mumble -l authors -d 'Show the Mumble authors'
complete -c mumble -l third-party-licenses -d 'Show licenses for third-party software used by Mumble'
complete -c mumble -l window-title-ext -d 'Sets a custom window title extension'
complete -c mumble -l dump-input-streams -d 'Dump PCM streams at various parts of the input chain (useful for debugging pu…'
complete -c mumble -l print-echocancel-queue -d 'Print on stdout the echo cancellation queue state (useful for debugging purpo…'

