// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1653302323);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("autoadmin.global_config_url", "file:///home/tommi/.firedragon/firedragon.overrides.cfg");
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "strict");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.migration.version", 125);
user_pref("browser.newtabpage.activity-stream.impressionId", "{842bac34-3ba4-4f35-bddd-b4b94270f5b3}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.addSearchEngines", "Qx72Jvr3/biz+aksHfhQmw==");
user_pref("browser.policies.runOncePerModification.extensionsInstall", "[\"https://addons.mozilla.org/firefox/downloads/file/3365502/sweet_dark-4.0-an+fx.xpi\",\"https://addons.mozilla.org/firefox/downloads/file/3933192/ublock_origin-1.42.4-an+fx.xpi\",\"https://addons.mozilla.org/firefox/downloads/file/3938065/dark_reader-4.9.50-an+fx.xpi\"]");
user_pref("browser.policies.runOncePerModification.extensionsUninstall", "[\"google@search.mozilla.org\",\"bing@search.mozilla.org\",\"amazondotcom@search.mozilla.org\",\"ebay@search.mozilla.org\",\"twitter@search.mozilla.org\"]");
user_pref("browser.policies.runOncePerModification.removeSearchEngines", "[\"Google\",\"Bing\",\"Amazon.com\",\"eBay\",\"Twitter\"]");
user_pref("browser.policies.runOncePerModification.setDefaultSearchEngine", "Garuda searX");
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1653302295527");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1653323895527");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1653302294");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.lastColdStartupCheck", 1653302293);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.toolbars.bookmarks.visibility", "always");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"addon_darkreader_org-browser-action\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"addon_darkreader_org-browser-action\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("distribution.garudalinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "100.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "d3fd9f868a064571aedec82317c537f1");
user_pref("dom.security.https_only_mode_ever_enabled", true);
user_pref("extensions.activeThemeID", "{59f619c8-220b-4a27-8918-bf1537bc060a}");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.lastAppBuildId", "20220522175204");
user_pref("extensions.lastAppVersion", "100.0.2");
user_pref("extensions.lastPlatformVersion", "100.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.addon@darkreader.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"5dedfd9c-fd74-4648-aeb2-0aeb7f1b6af0\",\"pictureinpicture@mozilla.org\":\"234e3810-89ae-4b5f-b2a4-717035035189\",\"screenshots@mozilla.org\":\"5c93a530-0733-4ae7-9195-89f25ad0ff86\",\"webcompat@mozilla.org\":\"4fc8da95-836c-4bb4-8617-0b3a0fff2a1c\",\"browser-mon@xdman.sourceforge.net\":\"7efcd62c-514e-478a-934a-85d13edc3957\",\"plasma-browser-integration@kde.org\":\"41c28fe5-6f92-4d89-8f28-1c1c03dca9e4\",\"default-theme@mozilla.org\":\"9bbc6b55-03f5-41d6-97e1-e7f968048e1c\",\"addon@darkreader.org\":\"62b25e2b-228a-4e23-9683-7874d5045f79\",\"uBlock0@raymondhill.net\":\"6a16bd1e-4dbf-4e63-aa0c-060ff4aa46e4\",\"{59f619c8-220b-4a27-8918-bf1537bc060a}\":\"ff95c41e-b58b-4e7d-b067-05e6195bcaac\",\"addons-search-detection@mozilla.com\":\"3d175fa7-398d-4382-9525-6c22d7bbe224\",\"google@search.mozilla.org\":\"265f9cd1-3222-45f7-b010-b1d4591bab46\",\"amazondotcom@search.mozilla.org\":\"fef42a8b-36f4-4ad4-afec-e03817344cf6\",\"wikipedia@search.mozilla.org\":\"58713a1d-c922-4983-9f02-afe7710c7b86\",\"bing@search.mozilla.org\":\"06a2cc6e-fd53-46d2-9d46-4a192e3267e4\",\"ddg@search.mozilla.org\":\"60723ffe-016d-4bd4-a599-44bda7d498db\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1653302294);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("intl.accept_languages", "en-US, en");
user_pref("javascript.use_us_english_locale", true);
user_pref("media.gmp-manager.buildID", "20220522175204");
user_pref("media.gmp-manager.lastCheck", 1653302358);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.http.referer.disallowCrossSiteRelaxingDefault.top_navigation", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.annotate_channels.strict_list.enabled", true);
user_pref("privacy.history.custom", true);
user_pref("privacy.partition.network_state.ocsp_cache", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.trackingprotection.socialtracking.enabled", true);
user_pref("security.sandbox.content.tempDirSuffix", "8683a8fa-7708-4a3d-b48a-a6a5b2085620");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1653302291);
user_pref("toolkit.telemetry.cachedClientID", "32e181af-1e77-4c69-9636-301753fa8163");
